# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=128, unique=True)),
                ('ip', models.CharField(max_length=64)),
                ('protoclo', models.CharField(max_length=16)),
                ('port', models.CharField(max_length=16)),
                ('uanme', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=128)),
                ('remarks', models.CharField(max_length=256)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
