# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='uanme',
            new_name='uname',
        ),
    ]
