# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20180904_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(max_length=8),
        ),
    ]
